[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "cups", "dbus", "expat", "libdrm", "libxkbcommon", "mesa", "libGL"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]
